### ISSUE TITLE
[UI] Toast add while Signup and Login 

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#104]
I would like to implement toast notifications for both the Login and Signup processes. When a user successfully logs in or encounters an error, we should display a toast message. You can use any toast library for this purpose

**Comment by Devrishi-Dutta** [comment]
can I work on this issue?

**Comment by Saurav-Pant** [comment]
Go ahead @Devrishi-Dutta
