### ISSUE TITLE
 Identify your own blood group compatibility.

### ISSUE THREAD

**Issue by VanshSh** [Saurav-Pant/Blood-Donation-Project#107]
**This feature on the Homepage will let the user know all the compatible blood groups for their own blood group.**
Example: 

| Recipient Blood Type | Matching Donor Blood Type |
|--|--|
| A+ | A+, A-, O+, O- |

Though I am confused should I make it a functionality (like take the input from the user and then show the data) or just show the data in the table format?

But I will figure it out and will do something that is easy for the user.

**Comment by VanshSh** [comment]
@Saurav-Pant Please assign the tag. So that I can start it.

**Comment by Saurav-Pant** [comment]
Thanks for raising this, Go ahead @VanshSh
