### ISSUE TITLE
Fix: The Sign Up and Login Routes are non-functional.

### ISSUE THREAD

**Issue by akash0708** [Saurav-Pant/Blood-Donation-Project#109]
The login and signup routes are currently not functional. It can be fixed with some changes.

### Screenshot of the problem

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/110753356/49b40917-7305-4170-850f-839dd4be9ecd)

**Comment by Saurav-Pant** [comment]
Thanks for raising this issue, @akash0708. I haven't hosted the backend yet, which is why it's not working. I'm encountering errors while trying to get it hosted; however, it's functioning correctly locally
