### ISSUE TITLE
bug: Inconsistent Navigation Display on Medium Devices - Missing Hamburger Menu

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#14]
On the website, when viewing the medium-sized device, the navigation bar displays the text one down another, To resolve this inconsistency and improve user experience, it is necessary to implement a hamburger menu for medium devices as well, similar to its display on small devices. This will ensure consistent navigation across different screen sizes and prevent layout disruptions.

Points:
Inconsistency in navigation display disrupts the user experience on medium devices.
Proposal: Implement a hamburger menu for medium devices, similar to small devices.
This will ensure consistent navigation and prevent layout disruptions on different screen sizes.

https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/7310145d-cf58-485e-b6a5-926c27a126e7

**Comment by Sarthak8874** [comment]
Hey,I would like to solve this issue.

**Comment by Saurav-Pant** [comment]
Thanks, it's now yours @Sarthak8874

**Comment by Saurav-Pant** [comment]
@Sarthak8874 , if you don't mind Plz Starred this repo

**Comment by Sarthak8874** [comment]
Created a pull request #24 Please check it
