### ISSUE TITLE
feat: Find All Donors 

### ISSUE THREAD

**Issue by srexrg** [Saurav-Pant/Blood-Donation-Project#140]
### What feature?

Instead of Finding Recipient based on blood group give all the recipients on the website and add the filter to filter based on the blood group. This increases the UI/UX of the website. I will be happy to work on this issue

### Add screenshots

![Screenshot 2024-05-11 010331](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/114612234/ad159cd0-3999-44ee-b538-5d7c5dca1a5f)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Go ahead @srexrg, Nice Idea

- But please share the UI of it or any rough idea of it.

**Comment by srexrg** [comment]
![Screenshot 2024-05-11 102629](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/114612234/5747172e-9293-4d34-8728-9970789a2715)
this will be the ui

**Comment by srexrg** [comment]
@Saurav-Pant can i do a pr ?

**Comment by Saurav-Pant** [comment]
Yes sure, do a PR @srexrg
