### ISSUE TITLE
sign in page

### ISSUE THREAD

**Issue by root-0101** [Saurav-Pant/Blood-Donation-Project#147]
### What's the style idea?

As sign up and sign in page are not same 

### Add screenshots

![Screenshot (74)](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/142779809/aecc9f97-e6a6-4a7f-a2e5-7304fea7fe8a)
![Screenshot (75)](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/142779809/9ec60bd6-2e85-4374-81f0-68569db0e08f)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Go ahead @root-0101

**Comment by root-0101** [comment]
I have done the required changes please check the PR
