### ISSUE TITLE
Misalignment of Navbar Heading on Small Devices

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#15]
The 'Register Now"  in the navbar of small devices is not aligned in the center like all other links, causing visual inconsistency. Requesting the 'Register Now' link to be centered for better design cohesion and user experience."

https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/812e0f4b-0370-4803-bd4d-26b4c57898e4

**Comment by manuel12** [comment]
Hello :) I would like to solve this issue, if that's ok.

**Comment by Saurav-Pant** [comment]
assigned, go ahead @manuel12
