### ISSUE TITLE
feat: Adding an AI bot

### ISSUE THREAD

**Issue by antriksh-9** [Saurav-Pant/Blood-Donation-Project#152]
### What feature?

An AI bot can enhance the user experience on a blood donation website by providing timely assistance, information, support throughout the donation process and screen donor eligibility.

### Add screenshots

![Screenshot 2024-05-12 014415](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/132576984/8915707e-40c5-42ba-8006-b165c503a624)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by antriksh-9** [comment]
Hey @Saurav-Pant, I want to work on this issue. 
Please assign it to me under GSSoC '24.

**Comment by Saurav-Pant** [comment]
Thanks for raising this, I'm also thinking of a similar one. 
Go ahead @antriksh-9

**Comment by SuhaniStark** [comment]
Under GSSoC'24, I would like to work on this issue, please assign it to me.

**Comment by antriksh-9** [comment]
Hey @Saurav-Pant, I encountered this error: `Error: @clerk/clerk-react: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.` when I tried to run the website locally. 
Please help me with this. 

![Screenshot 2024-05-17 230757](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/132576984/a57184e2-e220-4b94-b7b4-b90aaf6df6ad)

**Comment by Devvart1** [comment]
@Saurav-Pant same Issue I was facing Please help

**Comment by Saurav-Pant** [comment]
log in to [Clerk](https://clerk.com/) create one application and select these options (Chk Pic)
![clerk](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/a776a3a3-1372-4897-9113-0a464bc66b1e)

rename .env.example to .env and in place of these paste your own stuff

NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=

If you stuck in anyplace feel free to ping me

**Comment by antriksh-9** [comment]
Hey @Saurav-Pant,
Now this error is arising, it is probably coming from `defaultTheme` in `ThemeProvider` (`defaultTheme="system"`)
This file may contain space or in `Tailwind Configuration`  or any class name in the code. 

![Screenshot 2024-05-18 200622](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/132576984/7a20fb60-cc86-4363-83f1-d46eedbaf347)

**Comment by Devvart1** [comment]
@Saurav-Pant yes same

**Comment by Saurav-Pant** [comment]
hey please again clone the repo and then check @antriksh-9 @Devvart1

**Comment by Devvart1** [comment]
okay that issue is resolved, its running in local, but now its not fetching blood data

**Comment by Devvart1** [comment]
@Saurav-Pant I have raised a PR, please Review
