### ISSUE TITLE
[style]: Adding some animations in the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Saurav-Pant/Blood-Donation-Project#155]
### What's the style idea?

Adding some animations in the website.
animations like scrolling animations
tech stack to be used
-aos.js
-ityped.js
-tilt.js

### Add screenshots

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/125277258/f510c3b0-c489-45fb-bf84-b772b6455946)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by ARPITBAJPAI0098** [comment]
hello boss can you pls assign this issue to me i am having 1year of experience in Mern stack currently serving as the Technical Executive  of Sphnix largest techfest of Rajasthan under NIT jaipur
