### ISSUE TITLE
Bug: Shift Theme Toggle Button to Footer

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#156]
### What happened?

I want in left of the GitHub icon in the Footer, the toggle button needs to be. 

### Add screenshots

![Screenshot from 2024-05-12 23-22-43](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/d2e0b4bb-6638-4ea4-aa07-5a21a51981d7)
![Screenshot from 2024-05-12 23-22-34](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/2a0d6bb4-bda7-4e91-8ab0-8ebc7d4ce6a4)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [ ] I want to work on this issue

**Comment by StephCurry07** [comment]
you mean the toggle dark mode button should be left of the github icon?

**Comment by StephCurry07** [comment]
can you assign this to me after you clarify this?

**Comment by Saurav-Pant** [comment]
I want the toggle button, which is currently present on the navbar, to be positioned on the footer, to the left of the GitHub icon, Assigned to you.
