### ISSUE TITLE
GitHub Actions Workflows Not Triggering on Pull Request and Issue  

### ISSUE THREAD

**Issue by RangojuNandini** [Saurav-Pant/Blood-Donation-Project#158]
### What happened?

We've encountered issues with the GitHub Actions workflows configured to respond to newly opened pull requests and issues by adding comments. Despite being configured to trigger on pull request and issue opening events, the workflows fail to execute when pull requests and issues are opened in the repository.

![blood donation action bot issue](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/168331935/c83813d8-95e3-47a9-8977-fc435bdf729b)

### Add screenshots

I am keen to work on resolving this issue and getting our GitHub Actions workflows back on track. I will carefully review the workflow configurations and associated code to identify any potential issues and make the necessary adjustments to ensure that the workflows trigger correctly.After implementing the required fixes, the updated version would appear as follows,the display message will be the same as you provided.

![action 2](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/168331935/e4a985c5-d975-42da-af39-10a9d856b8a6)

**I would like to work on this issue under GSSoC 2024.Please assign this issue to me.**

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Go ahead @RangojuNandini

**Comment by RangojuNandini** [comment]
Thank you for assigning me the project. I'm ready to dive in and get started!

I request you to add a label of **level.**

Level 1: 10 points
Level 2: 25 points
Level 3: 45 points

**Comment by SuhaniStark** [comment]
Under GSSoC'24, I would like to work on this issue, please assign it to me.

**Comment by Saurav-Pant** [comment]
@SuhaniStark, @RangojuNandini is working on this issue, so you can check another issue.
