### ISSUE TITLE
GitHub Actions Workflow Failing on Issue Creation Event

### ISSUE THREAD

**Issue by RangojuNandini** [Saurav-Pant/Blood-Donation-Project#159]
### What happened?

We've encountered issues with our GitHub Actions workflow configured to respond to newly opened issues. Despite being configured to trigger on issue opening events, the workflow fails to execute when issues are opened in the repository.

![issue fail 3](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/168331935/ea8b5e22-6325-4c2d-8f0c-aee03fe2c7b5)

- The workflow fails to trigger when new issues are opened in the repository.
- Error emails and notifications are received when raising an issue without adding a pull request.

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/168331935/e3a7aae3-c41e-430a-8010-0dc432ffdd34)

### Add screenshots

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/168331935/b69cf4f0-49e8-4d98-ad6e-dc8420fba562)

**I would like to work on ths issue under GSSoC 2024.I request you to assign it to me.**

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
GO ahead @RangojuNandini

**Comment by RangojuNandini** [comment]
Thank you for assigning me the project. I'm ready to dive in and get started!

I request you to add a label of **level.**

**Comment by SuhaniStark** [comment]
Under GSSoC'24, I would like to work on this issue, please assign it to me.
