### ISSUE TITLE
[style]: Making Find blood page better

### ISSUE THREAD

**Issue by Rakshit-gen** [Saurav-Pant/Blood-Donation-Project#161]
### What's the style idea?

The find blood page looks like this.
We can add some good styling to dropdown and the donators cards to make the website look more interactive.

### Add screenshots

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/64471316/d3caaaca-251f-42de-a0b9-6684997fb2ba)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Rakshit-gen** [comment]
Sure I tried editing the styling a bit.

See if you like it

Dark theme:
![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/64471316/43fbee85-c505-4858-b958-7c3c8d3b9948)

Light theme:
![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/64471316/3c943a96-f421-4ffb-83de-7c3861e49931)

**Comment by Saurav-Pant** [comment]
Yeah, Looks Awesome

**Comment by Rakshit-gen** [comment]
Sending a PR

**Comment by StephCurry07** [comment]
for me the find blood page is not working.

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/76783882/037e7cfd-9a42-4dbe-9c7d-24f7e0475394)
Can you check it?

**Comment by Rakshit-gen** [comment]
@StephCurry07 it is because you don't have access to the database.

So you can't access that page because it uses data from the database.

**Comment by StephCurry07** [comment]
oh but previously 2 days ago it was opening... did it change afterwards?

**Comment by Rakshit-gen** [comment]
I have no idea of that. Maybe you can ask the project admin!

**Comment by Saurav-Pant** [comment]
@StephCurry07 just create your own db on mongodb atlas and place the Database URL on .env file (change .env.example to .env) 

DATABASE_URL="put here"

and add some random blood donor so you can check them

**Comment by Rakshit-gen** [comment]
Hey @Saurav-Pant can you please take a look at my pr and merge it if it's good enough?

**Comment by SuhaniStark** [comment]
Under GSSoC'24, I would like to work on this issue, please assign it to me.
