### ISSUE TITLE
[style]: Landing Page UI updation

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#163]
### What's the style idea?

we want to add a circle, so it looks good , if you want to take this please share a video after implementing it.

### Add screenshots

![UI change](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/476714a5-560c-42f2-846f-a15400f0c508)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [ ] I want to work on this issue

**Comment by shaman-004** [comment]
can you assign this issue to me @Saurav-Pant

**Comment by Saurav-Pant** [comment]
Sure, Go ahead @shaman-004

**Comment by shaman-004** [comment]
![Screenshot 2024-05-16 103159](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/93532515/aefcaacc-2f7c-42b2-8001-2470fa62ba8e)
can you help me on this @Saurav-Pant

**Comment by Saurav-Pant** [comment]
Thanks for working on the issue @shaman-004.

Please log in to [Clerk](https://clerk.com/) create one application and select these options (Chk Pic)
rename .env.example to .env and in place of these paste your own stuff

![clerk](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/36563525-a4c2-48e9-b107-0e1d5c0dde43)


NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=

If you stuck in anyplace feel free to ping me

**Comment by shaman-004** [comment]
Its working thank you @Saurav-Pant

**Comment by shaman-004** [comment]
Hello, @Saurav-Pant I have given a pull request can you pls check..
