### ISSUE TITLE
feat: Adding Toast Message 

### ISSUE THREAD

**Issue by AyushGakre** [Saurav-Pant/Blood-Donation-Project#174]
### What feature?

Adding toast while Register Donor and Organization

### Add screenshots

<img width="1107" alt="Screenshot 2024-05-16 at 9 51 48 PM" src="https://github.com/Saurav-Pant/Blood-Donation-Project/assets/122914231/c5170889-da17-4921-a77a-e2022835223f">

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Awesome, Idea, Go ahead @AyushGakre

**Comment by antriksh-9** [comment]
Hey @AyushGakre, I encountered this error: `Error: @clerk/clerk-react: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.` when I tried to run the website locally.
Can you help me with this?
