### ISSUE TITLE
feat: Implement "Thank you for registration" page

### ISSUE THREAD

**Issue by linhphan03** [Saurav-Pant/Blood-Donation-Project#180]
### What feature?

After registering for blood, donor / organization should be redirected to Thank you page

### Add screenshots

- 

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
NIce Idea, Share the approach please, Where we can add this(route)

**Comment by Saurav-Pant** [comment]
Go ahead @linhphan03
