### ISSUE TITLE
Bug: Change Recipient Details to Donator Details

### ISSUE THREAD

**Issue by linhphan03** [Saurav-Pant/Blood-Donation-Project#181]
### What happened?

Should it be Donator details instead of Recipient Details?

### Add screenshots

<img width="1512" alt="Screenshot 2024-05-17 at 3 28 13 AM" src="https://github.com/Saurav-Pant/Blood-Donation-Project/assets/122738041/52ca3454-8fd7-4ff8-acc8-f8011ab14bd4">

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Yeah, Nice Catch
