### ISSUE TITLE
feat: Create a "GetBlood" Component for the Home Section  

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#2]
I am requesting to develop a new component called "GetBlood" for the  Home section. This component will allow users to easily find and request blood donations. The screenshot below illustrates the desired layout and functionality. Please implement this feature to enhance the user experience and facilitate the process of obtaining blood donations.

![getblood](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/919a35af-88d9-4db8-a91b-695978198627)

**Comment by Ida-Naliaka** [comment]
Can I take this issue?

**Comment by Saurav-Pant** [comment]
off course, it is your's, assigned to you @Ida-Naliaka
