### ISSUE TITLE
feat: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [Saurav-Pant/Blood-Donation-Project#205]
### What feature?

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks

### Add screenshots

![PR merged](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/115717746/929eea05-23c6-4c80-802b-1e72b1a52109)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Saurav-Pant please assign me this issue under gssoc'24

**Comment by Saurav-Pant** [comment]
Go ahead @Asymtode712
