### ISSUE TITLE
feat: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [Saurav-Pant/Blood-Donation-Project#207]
### What feature?

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Add screenshots

![Close Old PRs](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/115717746/dcf213bc-186b-4441-8a52-a45c0a0f914d)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Saurav-Pant please assign me this issue under gssoc'24

**Comment by Saurav-Pant** [comment]
Here add the time span more than 3 months
