### ISSUE TITLE
feat: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [Saurav-Pant/Blood-Donation-Project#208]
### What feature?

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Add screenshots

![issue closed](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/115717746/b7f48d51-241b-4c18-86f2-f9a452f4635c)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Saurav-Pant please assign me this issue under gssoc'24

**Comment by Saurav-Pant** [comment]
Go ahead @Asymtode712
