### ISSUE TITLE
[style]: Hover efffect on top left side icon

### ISSUE THREAD

**Issue by devlohani99** [Saurav-Pant/Blood-Donation-Project#220]
### What's the style idea?

Hover effect can be added

### Add screenshots

![Screenshot 2024-05-24 011053](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/142163543/b75f77d0-e6fa-4cd6-b241-b1ba0e532603)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by devlohani99** [comment]
@manuel12 @ishika2021 @growupanand @mohammadanang kindly give me a attempt

**Comment by Saurav-Pant** [comment]
For Now, It's not needed @devlohani99 , Please check another issue
