### ISSUE TITLE
Bug: Image not correct

### ISSUE THREAD

**Issue by aryansharma220** [Saurav-Pant/Blood-Donation-Project#225]
### What happened?

There should be relevant images on these cards.

### Add screenshots

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/133234867/f91254be-3b5c-4570-9d0a-a0a4acb686a6)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
For now not needed this stuff, please check another issues @aryansharma220
