### ISSUE TITLE
Bug: Cards not responsive

### ISSUE THREAD

**Issue by aryansharma220** [Saurav-Pant/Blood-Donation-Project#226]
### What happened?

The cards are not responsive, text inside them are not readable in small screen.

### Add screenshots

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/133234867/64881a79-d297-44d6-84ad-22e3af3a035d)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Go ahead @aryansharma220
