### ISSUE TITLE
feat: Add Mail Option in Footer

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [Saurav-Pant/Blood-Donation-Project#229]
### What feature?

In the footer of the website, I will include a mail icon. When users click on this icon, they will be seamlessly redirected to their default email client with the "To:" field pre-filled with the email address. This will simplify the process of contacting via email and improve user experience.

 It will contribute to better communication with audience and facilitate timely responses to their inquiries.

### Add screenshots

No mail icon for now:

![gssoc16](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/128472306/2ad81a57-f6ac-4c9c-acec-09659bbfb4ef)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Ayesha-Siddiqua88** [comment]
@Saurav-Pant please assign this issue to me under GSSoC'24

**Comment by Saurav-Pant** [comment]
Go ahead @Ayesha-Siddiqua88 , please show the design of it before creating the PR

**Comment by Ayesha-Siddiqua88** [comment]
@Saurav-Pant This is how it looks
![finalmail](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/128472306/3b930981-89d5-41f4-a1b7-660480f4ab55)
