### ISSUE TITLE
Adding a scroll back to top button

### ISSUE THREAD

**Issue by sanskriti-lal** [Saurav-Pant/Blood-Donation-Project#249]
### What feature?

I propose adding a "Back to Top" button in the footer section of the website. This button will allow users to easily navigate back to the top or header section of the webpage with a single click, enhancing user experience and accessibility.

### Add screenshots

<img width="1419" alt="Screenshot 2024-06-12 at 4 44 20 PM" src="https://github.com/Saurav-Pant/Blood-Donation-Project/assets/165655543/b52ed3ba-935b-4497-9dc5-d4455db590c8">
the button will be added there

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Thanks for raising this, I have assigned the same issue to someone else, please check another issues
