### ISSUE TITLE
Blood Group list not Visible

### ISSUE THREAD

**Issue by kumarankit999** [Saurav-Pant/Blood-Donation-Project#25]
In the Recipient Details the Blood group is not visible, it is being totally white and we have to search it  then we are able to see the selected Blood group option.
Make the Font color from white to black . So, that we are able to see the available blood groups 

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/111564362/26051e14-ff58-4c86-a41b-a22daa1a79d4)

**Comment by manuel12** [comment]
@Saurav-Pant Hello I would like to fix this if that's ok :)

**Comment by Saurav-Pant** [comment]
> I see that the issue is not limited to blood group text not being visible. None of the input text are visible and also the button outlines are not visible in dark mode. I will include fixes for all of this on my PR.
> 
> ![image](https://user-images.githubusercontent.com/4129325/248852810-242fa757-1c5a-4ba5-8c06-1990d7e87b78.png)

Sure, you will change where you think, after i will check

**Comment by kumarankit999** [comment]
That's great @manuel12
