### ISSUE TITLE
[feature] : Redesign the form

### ISSUE THREAD

**Issue by sivaprasath2004** [Saurav-Pant/Blood-Donation-Project#253]
### What feature?

- In this project `sign Up` and  `sign In` page cannot approach dark mode pattern.
- please assign me ... :rocket: 

### Before

![Screenshot from 2024-06-14 20-51-51](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/121082414/6c4c669c-9055-4e6e-a707-07068138bd1c)

### After

![Screenshot from 2024-06-14 20-51-42](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/121082414/34e8d588-6413-4379-a762-96280227cd74)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Thanks for creating but for now, we are okay with the current design so please check another issue @sivaprasath2004
