### ISSUE TITLE
Feature ✨: Add scroll to top button 

### ISSUE THREAD

**Issue by Tejashri-Taral** [Saurav-Pant/Blood-Donation-Project#255]
### What feature?

I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Add screenshots

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/160386036/3e8512e6-9309-4d38-95be-df59c2d37591)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
For Now, I have assigned the same issue to someone else so please check another issue
