### ISSUE TITLE
feat:Add country code

### ISSUE THREAD

**Issue by AkhilaSunesh** [Saurav-Pant/Blood-Donation-Project#257]
### What feature?

Add country code in phone number as a drop down

### Add screenshots

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/140897461/f6c5365a-5850-423c-9727-f36f04128ea7)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
Mainly for now we not needed this, so please check another issue @AkhilaSunesh
