### ISSUE TITLE
feat: Google SignUp Functionality

### ISSUE THREAD

**Issue by codercake** [Saurav-Pant/Blood-Donation-Project#269]
### What feature?

Authentication is a crucial aspect of modern web applications, ensuring that only authorized users can access certain features or data. Implementing Google Sign-In allows users to log in or register using their existing Google account credentials, streamlining the authentication process and enhancing security. This functionality leverages OAuth 2.0 protocols to authenticate users via Google's services, reducing the need for users to remember separate usernames and passwords for different applications.

### Add screenshots

![image](https://github.com/user-attachments/assets/0fbf6f25-cc51-4f91-9e6e-bd2c2ad50f5a)

### Record

- [X] I have checked the existing [issues](https://github.com/Saurav-Pant/Blood-Donation-Project/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/Saurav-Pant/Blood-Donation-Project/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by Saurav-Pant** [comment]
This is present in the website, Closing this for now
