### ISSUE TITLE
Input Text on register forms are not dark  mode compatible

### ISSUE THREAD

**Issue by vivekrawat21** [Saurav-Pant/Blood-Donation-Project#27]
In the Register Forms in both Register as donor and Register as Organisation  the input value  is not visible when we switch it  toDark mode 
<h2>Register donor form : </h2>

[Screencast from 2023-06-26 23-26-48.webm](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/116631005/0a0702a4-27a1-4d59-a2a5-0dcb387771be)

<h2>Register org fom</h2>

[Screencast from 2023-06-26 23-27-28.webm](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/116631005/77b60e88-df38-4be8-99c6-f7aee41ad398)

**Comment by manuel12** [comment]
@Saurav-Pant I can take this :)

**Comment by Saurav-Pant** [comment]
it's yours now, @manuel12
