### ISSUE TITLE
Forms are not responsive

### ISSUE THREAD

**Issue by vivekrawat21** [Saurav-Pant/Blood-Donation-Project#28]
The register donor form and register organisation forms are not responsive for small screen devices 

[Screencast from 2023-06-26 23-35-43.webm](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/116631005/f2c8ef3e-4cf5-4097-96af-50d56104a590)

**Comment by Saurav-Pant** [comment]
@manuel12 Thanks, it's now yours
