### ISSUE TITLE
Outdated Twitter Logo 

### ISSUE THREAD

**Issue by LynxSumit** [Saurav-Pant/Blood-Donation-Project#43]
[Issue] Title:

Update Outdated Twitter Icon

Issue Description:

Problem:
![Screenshot 2023-09-28 215453](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/114245865/15b58ae6-84b7-4e96-8d28-a5e4e7221318)

The project currently utilizes an outdated Twitter icon.

Request:

I kindly request that the project's maintainer update the Twitter icon to the latest version provided by Twitter's official branding guidelines. This will ensure the project maintains a contemporary and accurate representation of the Twitter brand.

Thank you for considering this request.

**Comment by vibh1103** [comment]
Hi can i pick this task ?

**Comment by Saurav-Pant** [comment]
Thanks @vibh1103 , go ahead 

> Hi can i pick this task ?

**Comment by vibh1103** [comment]
Can we wait for 1 oct i will raise the PR. when the event start 😃
