### ISSUE TITLE
ES Lint issues in Client folder to improve code quality

### ISSUE THREAD

**Issue by vibh1103** [Saurav-Pant/Blood-Donation-Project#44]
[eslint] 
src/components/donorForm.jsx
  Line 7:18:  'toggleTheme' is assigned a value but never used  no-unused-vars

src/components/orgForm.jsx
  Line 5:18:  'toggleTheme' is assigned a value but never used  no-unused-vars

src/context/AuthContext.js
  Line 8:10:   'tokenOne' is assigned a value but never used      no-unused-vars
  Line 12:11:  'storedToken1' is assigned a value but never used  no-unused-vars
  Line 27:9:   'token1' is assigned a value but never used        no-unused-vars

src/pages/findBlood.jsx
  Line 7:18:  'toggleTheme' is assigned a value but never used                                                              no-unused-vars
  Line 41:6:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint] 
src/components/donorForm.jsx
  Line 7:18:  'toggleTheme' is assigned a value but never used  no-unused-vars

src/components/orgForm.jsx
  Line 5:18:  'toggleTheme' is assigned a value but never used  no-unused-vars

src/context/AuthContext.js
  Line 8:10:   'tokenOne' is assigned a value but never used      no-unused-vars
  Line 12:11:  'storedToken1' is assigned a value but never used  no-unused-vars
  Line 27:9:   'token1' is assigned a value but never used        no-unused-vars

src/pages/findBlood.jsx
  Line 7:18:  'toggleTheme' is assigned a value but never used                                                              no-unused-vars
  Line 41:6:  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

**Comment by vibh1103** [comment]
I can pick this issue also @Saurav-Pant

**Comment by Saurav-Pant** [comment]
Sure I will assign you, Firstly tell me How you approach this @vibh1103

**Comment by vibh1103** [comment]
run eslint on the project and then try to solve the issue file by file which is not solved. 

For long term we can do one thing we can create a npm command to solve those linting issues.

**Comment by Saurav-Pant** [comment]
Great, Go ahead @vibh1103
