### ISSUE TITLE
 Convert MongoDB Connection to async/await

### ISSUE THREAD

**Issue by durgaprasad118** [Saurav-Pant/Blood-Donation-Project#45]
- I propose updating our MongoDB connection to use async/await. 
- Also using try/catch 

It would be great if you would assign me to handle the conversion. Thankyou.
![Async issue](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/108184152/e4dd9092-53df-4941-a258-98599e05b2e0)

**Comment by Saurav-Pant** [comment]
Thanks for raising issue, Go ahead, @durgaprasad118

**Comment by durgaprasad118** [comment]
Sure. Thankyou

**Comment by durgaprasad118** [comment]
Done ✅
Can close this issue. Thankyou

**Comment by Saurav-Pant** [comment]
Sure @durgaprasad118, Next time if you Create a PR also type Closed:  issue Number
Thanks

**Comment by durgaprasad118** [comment]
Sure 🙌
