### ISSUE TITLE
Improvement in Readme File

### ISSUE THREAD

**Issue by durgaprasad118** [Saurav-Pant/Blood-Donation-Project#46]
## Improvement in Readme File
1. describing the path to server as described for server
![Screenshot from 2023-09-30 19-45-13](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/108184152/29c82dd5-7e88-495a-90a6-6fcf5b5a0b40)

2. Alignment of the Start Server point number(4)
3.  Point (4) is repeated twice instead of 5 
4.  After installing the packages **it is neccessary to pull from the main repository so that our local repo remains updaed**
5. I would suggest to create a branch first and then `track changes ` and `commit the changes`
6.  Add another point describing how to create a pull request *Explaing changes*

- These are the changes i would like to propose to change in the Readme file
- It would be great if you would assign me to handle the conversion. **Thankyou.**

**Comment by Saurav-Pant** [comment]
Thanks for raising this issue, It's yours now @durgaprasad118
