### ISSUE TITLE
Enhancement: Add More States and Respective Capitals in Dropdown Menus

### ISSUE THREAD

**Issue by shishiro26** [Saurav-Pant/Blood-Donation-Project#48]
Currently, the registration dropdowns only include Uttarakhand in the list of states. We propose expanding the options by adding more states and their respective capitals. This enhancement aims to provide users with a comprehensive selection, ensuring accurate location data for both donors and organizations during the registration process. I am enthusiastic about working on this enhancement as part of Hacktoberfest.

**Comment by Saurav-Pant** [comment]
Thanks for raising this, Go ahead @shishiro26
