### ISSUE TITLE
Add Feature : User profile in header after sign In

### ISSUE THREAD

**Issue by Madanraj0519** [Saurav-Pant/Blood-Donation-Project#50]
My feature request is to show the User profile in the header after the user sign in into the page. It helps the user to view their profile, add their user profile image, edit their profile, and then log out from the page.

**Comment by Madanraj0519** [comment]
I'm willing to create this feature in this project

**Comment by Saurav-Pant** [comment]
Thanks for raising this issue, It will great addition to the project,Go ahead @Madanraj0519

**Comment by Saurav-Pant** [comment]
@Madanraj0519, generally, after successfully logging in, we can see the user icon at the top. If someone clicks on this icon, it will redirect them to their personal dashboard. So, please run both the client and server so that it will run properly, and you can see this.
