### ISSUE TITLE
Add Padding for signup and Sign in cards for mobile devices And Changing sign In in Sign Up seciton

### ISSUE THREAD

**Issue by durgaprasad118** [Saurav-Pant/Blood-Donation-Project#53]
1. For mobile devices the card is taking full width and only top and bottom part of the card is visible would like to change it
![Screenshot from 2023-10-02 02-27-31](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/108184152/1323f33f-96dc-41ec-a349-97e39657b513)

![Screenshot from 2023-10-02 02-27-24](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/108184152/cf81c8d8-3f4a-41ca-acdf-0a6c02dd43c2)

2. In the SignUp page it is written as Sign In instead of **Sign Up**
![SignIn to SignUp](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/108184152/abffb820-0bde-4ccc-8780-1ae01ba6ec5e)

**I would like to make the above changes and it would be great if you assign me todo the same. Thankyou**

**Comment by Saurav-Pant** [comment]
Sounds good, Go ahead @durgaprasad118
