### ISSUE TITLE
SignUp input text-Align and Favicon addition

### ISSUE THREAD

**Issue by durgaprasad118** [Saurav-Pant/Blood-Donation-Project#54]
- While entering the email and password in **Signup and Login** sections it's starting from the center 
![Screenshot from 2023-10-02 02-56-26](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/108184152/832c73e6-e448-4c5b-9ac8-60535484604b)

- Adding a favicon to the webite
![Screenshot from 2023-10-02 02-30-53](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/108184152/a8c2e345-3b50-46f7-93cb-452c5e51ed90)

**I would like to fix this changes. It would be great if you could assign me to do the same.**

**Thankyou**

**Comment by Saurav-Pant** [comment]
Thanks for raising this, Before putting the Favicon please show me, then add it @durgaprasad118

**Comment by durgaprasad118** [comment]
Sure @Saurav-Pant
