### ISSUE TITLE
Wrong file name in README.md

### ISSUE THREAD

**Issue by Sahil-Choudhary-17** [Saurav-Pant/Blood-Donation-Project#58]
File name is Client but in README.md it is client.
I would like to work on this issue.

**Comment by Saurav-Pant** [comment]
Go ahead @Sahil-Choudhary-17

**Comment by Saurav-Pant** [comment]
Yeah, I did this by mistake, go ahead🎉

**Comment by Durgeshsejekar** [comment]
I wnat to work on this issue so please can u assign me.
