### ISSUE TITLE
Adding a "Sign In" Button to Enhance Navigation in the Navbar

### ISSUE THREAD

**Issue by shishiro26** [Saurav-Pant/Blood-Donation-Project#59]
I propose adding a "Sign In" button to the navigation bar to improve user experience and enhance the website's overall usability. 

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/113853868/71437073-c9f4-42b5-ad75-5a140beef4f2)

I would like to work on this issue

**Comment by Saurav-Pant** [comment]
Go ahead @shishiro26
