### ISSUE TITLE
ENHANCEMENT: Adding form validation with formik

### ISSUE THREAD

**Issue by Sahil-Choudhary-17** [Saurav-Pant/Blood-Donation-Project#60]
Instead of using built-in HTML5 form validation we can use a popular library like Formik for form validation.

**Comment by Saurav-Pant** [comment]
Yeah, I am thinking the same to do so, is you are here to pick this? @Sahil-Choudhary-17

**Comment by Saurav-Pant** [comment]
Nice @Sahil-Choudhary-17 , Go ahead 🎉

**Comment by Saurav-Pant** [comment]
Hey @Sahil-Choudhary-17 are you not working on this?

**Comment by Tanush-J** [comment]
can I take up this issue if no one is working on this?

**Comment by Saurav-Pant** [comment]
sure @Tanush-J , Go ahead

**Comment by Tanush-J** [comment]
I will add form validation to orgForm and donorForm. Is there any other form I should add validation to?

**Comment by Tanush-J** [comment]
I won't be able to work on this, someone else can go ahead with this issue 👍

**Comment by Saurav-Pant** [comment]
No worries @Tanush-J , Thanks for trying

**Comment by aarjun8060** [comment]
would you assign to me ?
I want to try in this issue. I already work on formik and yup .

**Comment by Saurav-Pant** [comment]
Go ahead @aarjun8060

**Comment by aarjun8060** [comment]
Check PR #123 @Saurav-Pant
