### ISSUE TITLE
BUG: homepage button has no action attached 

### ISSUE THREAD

**Issue by RahulMittal18** [Saurav-Pant/Blood-Donation-Project#63]
Homepage's "Get Blood Now" button should have an action attached to it i.e. event listener, may be to navigate to  the signup or signin page. I would like to fix it.

**Comment by abhi5hek001** [comment]
please assign this task to me @Saurav-Pant

**Comment by RahulMittal18** [comment]
Can you assign this to me? @Saurav-Pant
