### ISSUE TITLE
BUG: Not getting respective cities for states in orgnization form

### ISSUE THREAD

**Issue by vivekrawat21** [Saurav-Pant/Blood-Donation-Project#68]
[Screencast from 2023-10-02 22-38-58.webm](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/116631005/488f04aa-e8fb-41e5-8fc2-d9d88068fbd6)

**Comment by vivekrawat21** [comment]
assign me this :3

**Comment by JOSHIK27** [comment]
is this issue still open ? I see it is not fixed and looking forward to fixing this
