### ISSUE TITLE
bug:  Lack of Responsiveness and Missing Hamburger Menu

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#7]
The website suffers from responsiveness issues and lacks a hamburger menu, resulting in a subpar user experience. Elements are misaligned, cut off, and overlap on different screen sizes. The absence of a hamburger menu hampers navigation on smaller screens. These issues compromise the website's visual appeal and professionalism. To rectify the problem, a responsive design should be implemented to ensure seamless adaptability. Additionally, incorporating a hamburger menu for smaller screens will improve navigation and enhance user experience. Promptly addressing these issues is essential to deliver a modern, visually pleasing website that meets user expectations.

**Comment by Aryan123-rgb** [comment]
@Saurav-Pant Would like to work on this.

**Comment by Saurav-Pant** [comment]
assigned @Aryan123-rgb

**Comment by Aryan123-rgb** [comment]
https://github.com/Saurav-Pant/Blood-Donation-Project/assets/118872531/b1696f0a-5eb2-4427-886f-872bfdf02207

Successfully implemented the path the hamburger navbar. Please take a look at it .

**Comment by Saurav-Pant** [comment]
Thanks, You did an Amazing Job @Aryan123-rgb  Create PR for this.

**Comment by Saurav-Pant** [comment]
Merged
