### ISSUE TITLE
 Missing Banners and Collaborator Links

### ISSUE THREAD

**Issue by Venkateeshh** [Saurav-Pant/Blood-Donation-Project#76]
This issue is to address the absence of banners and links to collaborators in the Blood Donation Project repository. We need to ensure that the project's banners are correctly displayed, and links to collaborators are provided for better project visibility and collaboration.

**Comment by Saurav-Pant** [comment]
Do you want to work on it? @Venkateeshh

**Comment by Venkateeshh** [comment]
> Do you want to work on it? @Venkateeshh

Yes I would like to work on it.
