### ISSUE TITLE
UI: Uneven spaces in form 

### ISSUE THREAD

**Issue by Sayan-dev** [Saurav-Pant/Blood-Donation-Project#79]
## Also let the address field height be auto rather than fixed

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/42710260/141fefa6-a08a-48b6-be7b-43328b14f68c)

![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/42710260/81880fbe-d692-4964-bc0c-4e42a9558378)

**Comment by Sayan-dev** [comment]
I am working on it can you asign me? @Saurav-Pant.

**Comment by Saurav-Pant** [comment]
Go ahead @Sayan-dev
