### ISSUE TITLE
UI: Positioning issues for the illustrations

### ISSUE THREAD

**Issue by Sayan-dev** [Saurav-Pant/Blood-Donation-Project#80]
## Issue:
The cards and the illustration are not positioned properly, and the logos in the cards are not having proper positioning.  
![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/42710260/c34ef7e0-3562-4754-9eb6-ccad7276badb)

**Comment by Sayan-dev** [comment]
I am working on these, can you  assign me? @Saurav-Pant

**Comment by Saurav-Pant** [comment]
Go ahead, @Sayan-dev
