### ISSUE TITLE
UI: Signup button text error

### ISSUE THREAD

**Issue by Sayan-dev** [Saurav-Pant/Blood-Donation-Project#81]
## Issue
In Signup page, Sign up button is written as Sign in

## Reference
![image](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/42710260/22ad2d90-f9dd-4253-916f-ee41aa92d6c9)

**Comment by sanketshevare** [comment]
Can I work on this issue?

**Comment by Saurav-Pant** [comment]
Go ahead @sanketshevare

**Comment by Naveenraj0602** [comment]
Can you assign me this issue? @Saurav-Pant
