### ISSUE TITLE
log out loading bug

### ISSUE THREAD

**Issue by Naveenraj0602** [Saurav-Pant/Blood-Donation-Project#82]
when you click log out button in the navbar profile loading 

https://github.com/Saurav-Pant/Blood-Donation-Project/assets/108968940/761d1962-23fc-4916-8eb2-1cc7006c09b4

I would like to work on this issue, can you assign me @Saurav-Pant

**Comment by Saurav-Pant** [comment]
Thanks for raising this @Naveenraj0602, Go ahead
