### ISSUE TITLE
UI: Adding Blood-Donation related logos on mainpage

### ISSUE THREAD

**Issue by Abhishekdx300** [Saurav-Pant/Blood-Donation-Project#86]
![Screenshot 2023-10-05 212447](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/127688631/fd12f8f8-651d-4872-9a84-3dd7eb7c730e)

Will add different logos in those spaces. @Saurav-Pant  please assign it to me. I'm working on it.

**Comment by Saurav-Pant** [comment]
Thanks for raising this, assigned
