### ISSUE TITLE
UI: Find Blood Page UI Updation

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#87]
The user interface for the 'Find Blood ' route is currently **suboptimal** and **unresponsive**. If anyone is interested in improving the UI, please feel free to take on this issue
![make this page well](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/f08cc1dc-c627-4599-9839-9727a2526941)

**Comment by Paul-Annay** [comment]
This seems like an interesting task. Can I try to solve this?

**Comment by Saurav-Pant** [comment]
Of course, @Paul-Annay, thanks! I am assigning this task to you. Give it a try.
