### ISSUE TITLE
Add a select feature on register in nav bar and add link of registerDonor and registerOrg pages 

### ISSUE THREAD

**Issue by vivekrawat21** [Saurav-Pant/Blood-Donation-Project#9]
This feature will enhance the user experience and provide the option for users to register either as a donor or as an organization.

To implement this feature, I propose adding a select dropdown menu with two options: "Register as Donor" and "Register as Organization". Users can select their desired registration type before proceeding with the registration process.

This select feature will allow for better customization and adaptability to different user types. It will enable a smoother user journey, ensuring that the appropriate registration flow is presented based on the user's selection.

**Comment by Saurav-Pant** [comment]
Nice, But you need to add SS of that for Figma so anyone can understood, without running locally

**Comment by vivekrawat21** [comment]
![Screenshot from 2023-05-31 11-29-57](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/116631005/0a931040-d8b6-453b-8010-3c2d78e1e372)
Add a slect feature in register now buttom. Add two options  Donor and Organisation


![Screenshot from 2023-05-31 11-31-23](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/116631005/c052ee6f-f65f-453f-bdc9-84de0c28b74d)
Add route of the registerDonor and registerOrg in select option respectively

**Comment by vivekrawat21** [comment]
@Saurav-Pant  @faisalamin001  thanks,
<br>
<h3>Here is the SS<h3>
<br><br>
![Screenshot from 2023-05-31 14-55-22](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/116631005/2f44085a-9d6a-4069-9fdc-3fc2742019ad)
<br>
<br>
<h4>fFor further details you can refer to the figma design</h4>
<br>
https://www.figma.com/file/MRe8NbQUbD0R5tEqUOI2rn/Diagram---Blood-Donation-Website-(Community)?type=whiteboard&node-id=81-38&t=RPwgS74PXwoqpb3w-0

**Comment by vivekrawat21** [comment]
@Saurav-Pant  @faisalamin001  thanks,
<br>
<h3>Here is the SS<h3>
<br><br>

![Screenshot from 2023-05-31 14-55-22](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/116631005/b5fa4112-32e0-4628-a9eb-9f215cd57613)

<br><br>
<h4>For further details you can refer to the figma design</h4>
<br>

https://www.figma.com/file/MRe8NbQUbD0R5tEqUOI2rn/Diagram---Blood-Donation-Website-(Community)?type=whiteboard&node-id=81-38&t=RPwgS74PXwoqpb3w-0
