### ISSUE TITLE
[UI] Redesign Register as Donor and Register as Organization Change

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#94]
The 'Register as Organization' and 'Register as Donor' forms on the website do not have an appealing design. Therefore, we are looking to redesign them. If anyone is interested in taking on this task, please feel free to grab this issue.
![redesign these](https://github.com/Saurav-Pant/Blood-Donation-Project/assets/103263909/98c4187e-d26b-4068-bfe7-3b09e182130a)

**Comment by Chirag-Nanda** [comment]
can this issue be assigned to me?

**Comment by Saurav-Pant** [comment]
Of course, @Chirag-Nanda, how do you redesign this?

**Comment by Saurav-Pant** [comment]
BTW I assigned you. Thanks for taking care of it, Chirag

**Comment by Chirag-Nanda** [comment]
I am planning to use some form templates available in bootstrap

**Comment by Chirag-Nanda** [comment]
Is it fine by you?

**Comment by Saurav-Pant** [comment]
Please use Tailwind for this; Bootstrap is not well-suited for the task

**Comment by Chirag-Nanda** [comment]
Ok

**Comment by Saurav-Pant** [comment]
Chirag, are you okay with using Tailwind?

**Comment by Chirag-Nanda** [comment]
Yes, sure

**Comment by Chirag-Nanda** [comment]
@Saurav-Pant can you check my pull request? It is asking for your permission to deploy
