### ISSUE TITLE
sign up of this page doesn't work 

### ISSUE THREAD

**Issue by doppedheart** [Saurav-Pant/Blood-Donation-Project#96]
when creating a new user after filling in all the details the sumit button does not show anything or simply does not work

**Comment by doppedheart** [comment]
sign up with google and login also don't work

**Comment by doppedheart** [comment]
got the bug you are using a local server for backend while using vercel for hosting frontend that why it's not showing the signup functionality 
and also for the error its not notifing anything like a toast or something 
if possible assign me this issue and guide me to host the website to backend and make it production and local development compatible using env varible as a switch

**Comment by Saurav-Pant** [comment]
Thanks for raising this issue, @doppedheart. I haven't hosted the backend yet, which is why it's not working. I'm encountering errors while trying to get it hosted; however, it's functioning correctly locally

**Comment by doppedheart** [comment]
okay

**Comment by Saurav-Pant** [comment]
can you suggest which platform is best for hosting the backend?

**Comment by Vyomrana02** [comment]
@Saurav-Pant I can suggest this platform to host backend for free 
below is link of tutorial of hosting 
https://www.youtube.com/watch?v=q8GSWGu2roA&ab_channel=Raddy

**Comment by Saurav-Pant** [comment]
Thanks for this @Vyomrana02 we are migrating this to NextJS, so after that, this will work, if you want to work on it, you are welcome.
