### ISSUE TITLE
[UI] Changed Toggle Theme Button UI

### ISSUE THREAD

**Issue by Saurav-Pant** [Saurav-Pant/Blood-Donation-Project#97]
If anyone has any ideas related to the Toggle Theme UI updation, please share them with me. I'll assign the task to you if your idea aligns with our needs

**Comment by parag477** [comment]
Hey @Saurav-Pant I want to work on this.

**Comment by Saurav-Pant** [comment]
Thanks @parag477 , Go ahead

**Comment by parag477** [comment]
I have done the changes. Please check it and merge my pr.
